id = "FreeFreecam"
name = "FreeFreecam"
description = "Removes the Freecam restriction."
version = "1.0.1"
homepage = "https://github.com/x8c8r/webfishing"
author = "x8c8r"

icon = "icon.png"
readme = "README.md"

# both are optional here, pick what you want
[project]
csharp = "./FreeFreecam/FreeFreecam.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
