id = "YAAM"
name = "YAAM"
description = "Yet Another Autofishing Mod, featuring toggles for casting, reeling and mashing and other features."
version = "1.3.2"
homepage = "https://github.com/x8c8r/webfishing"
author = "x8c8r"

icon = "icon.png"
readme = "README.md"

# both are optional here, pick what you want
[project]
godot = "./GodotProject/project.godot"
csharp = "./YAAM/YAAM.csproj"

[[dependencies]]
id = "TackleBox"
thunderstore_version = "PuppyGirl-TackleBox-0.5.1"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"