
id = "Waypoints"
name = "Waypoints"
description = "Create waypoints and teleport to them at any point!"
version = "1.0.1"
homepage = "https://github.com/x8c8r/webfishing"
author = "x8c8r"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./Waypoints/Waypoints.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
