id = "StreamerMode"
name = "StreamerMode"
description = "Provides options to toggle things off for streamers to safely stream the game."
version = "1.0.0"
homepage = "https://github.com/x8c8r/webfishing"
author = "x8c8r"

icon = "icon.png"
readme = "README.md"

# both are optional here, pick what you want
[project]
csharp = "./StreamerMode/StreamerMode.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"